default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lean_update_development

test:
  <<: *default
  database: lean_update_test

production:
  <<: *default
  url: <%= ENV['LEAN_UPDATE_DATABASE_URL'] %>
